name: Build/release Electron app

on:
  push:

env:
  NODE_VERSION: 20.17.0

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci
      - run: npm run check:tsc

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run package:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run package:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run package:win

      - uses: actions/upload-artifact@v4
        with:
          name: package-app
          path: dist
